--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it




--
-- Name: acoes_automacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.acoes_automacao (
    id bigint NOT NULL,
    mensagem text,
    status_destino character varying(255),
    tipo character varying(255),
    regra_id bigint NOT NULL,
    tag_id bigint,
    CONSTRAINT acoes_automacao_status_destino_check CHECK (((status_destino)::text = ANY ((ARRAY['A_FAZER'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying])::text[]))),
    CONSTRAINT acoes_automacao_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['NOTIFICAR_RESPONSAVEL'::character varying, 'NOTIFICAR_MEMBROS_PROJETO'::character varying, 'MOVER_PARA_STATUS'::character varying, 'ADICIONAR_TAG'::character varying])::text[])))
);


--
-- Name: acoes_automacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.acoes_automacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acoes_automacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anexos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anexos (
    id bigint NOT NULL,
    caminho character varying(255),
    nome_arquivo character varying(255),
    tarefa_id bigint
);


--
-- Name: anexos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.anexos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anexos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comentarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comentarios (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    texto text,
    tarefa_id bigint,
    usuario_id bigint
);


--
-- Name: comentarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comentarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comentarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conquistas_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conquistas_usuario (
    id bigint NOT NULL,
    codigo character varying(255),
    desbloqueada_em timestamp(6) without time zone,
    usuario_id bigint NOT NULL,
    CONSTRAINT conquistas_usuario_codigo_check CHECK (((codigo)::text = ANY ((ARRAY['PRIMEIRA_TAREFA'::character varying, 'DEZ_TAREFAS'::character varying, 'CINQUENTA_TAREFAS'::character varying, 'CEM_PONTOS'::character varying, 'QUINHENTOS_PONTOS'::character varying, 'MULTIPROJETOS'::character varying])::text[])))
);


--
-- Name: conquistas_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conquistas_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conquistas_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentos_projeto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos_projeto (
    id bigint NOT NULL,
    atualizado_em timestamp(6) without time zone,
    categoria character varying(255),
    conteudo text,
    criado_em timestamp(6) without time zone,
    titulo character varying(255),
    criado_por bigint,
    projeto_id bigint NOT NULL,
    CONSTRAINT documentos_projeto_categoria_check CHECK (((categoria)::text = ANY ((ARRAY['DOCUMENTACAO_TECNICA'::character varying, 'REQUISITOS'::character varying, 'ARQUITETURA'::character varying, 'BANCO_DE_DADOS'::character varying, 'REGRAS_DE_NEGOCIO'::character varying, 'DECISOES'::character varying, 'RETROSPECTIVA_SPRINT'::character varying, 'OUTRO'::character varying])::text[])))
);


--
-- Name: documentos_projeto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos_projeto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_projeto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empresas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empresas (
    id bigint NOT NULL,
    codigo_convite character varying(255),
    criado_em timestamp(6) without time zone,
    nome character varying(255)
);


--
-- Name: empresas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.empresas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: epicos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.epicos (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    descricao text,
    titulo character varying(255),
    projeto_id bigint NOT NULL
);


--
-- Name: epicos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.epicos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.epicos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historias_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historias_usuario (
    id bigint NOT NULL,
    criterios_aceitacao text,
    descricao text,
    pontos integer,
    prioridade character varying(255),
    status character varying(255),
    titulo character varying(255),
    epico_id bigint,
    projeto_id bigint NOT NULL,
    sprint_id bigint,
    CONSTRAINT historias_usuario_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDA'::character varying])::text[])))
);


--
-- Name: historias_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historias_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historias_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico (
    id bigint NOT NULL,
    acao character varying(255),
    data timestamp(6) without time zone,
    tarefa_id bigint,
    usuario_id bigint
);


--
-- Name: historico_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.historico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: integracoes_github; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integracoes_github (
    id bigint NOT NULL,
    conectado_em timestamp(6) without time zone,
    repositorio_nome character varying(255),
    repositorio_owner character varying(255),
    token_acesso text,
    projeto_id bigint NOT NULL
);


--
-- Name: integracoes_github_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.integracoes_github ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.integracoes_github_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificacoes (
    id bigint NOT NULL,
    criado_em timestamp(6) without time zone,
    lida boolean NOT NULL,
    mensagem character varying(255),
    tarefa_id bigint,
    usuario_id bigint
);


--
-- Name: notificacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notificacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projeto_membros; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projeto_membros (
    projeto_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: projetos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projetos (
    id bigint NOT NULL,
    data_fim date,
    data_inicio date,
    descricao text,
    nome character varying(255),
    criado_por bigint,
    empresa_id bigint NOT NULL
);


--
-- Name: projetos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.projetos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projetos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: regras_automacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.regras_automacao (
    id bigint NOT NULL,
    ativa boolean NOT NULL,
    nome character varying(255),
    status_gatilho character varying(255),
    projeto_id bigint NOT NULL,
    CONSTRAINT regras_automacao_status_gatilho_check CHECK (((status_gatilho)::text = ANY ((ARRAY['A_FAZER'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying])::text[])))
);


--
-- Name: regras_automacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.regras_automacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.regras_automacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sprint_burndown_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sprint_burndown_snapshots (
    id bigint NOT NULL,
    data date,
    pontos_restantes integer,
    sprint_id bigint NOT NULL
);


--
-- Name: sprint_burndown_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sprint_burndown_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sprint_burndown_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sprints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sprints (
    id bigint NOT NULL,
    data_fim date,
    data_inicio date,
    nome character varying(255),
    objetivo text,
    status character varying(255),
    projeto_id bigint NOT NULL,
    CONSTRAINT sprints_status_check CHECK (((status)::text = ANY ((ARRAY['PLANEJADA'::character varying, 'ATIVA'::character varying, 'CONCLUIDA'::character varying])::text[])))
);


--
-- Name: sprints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sprints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sprints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    cor character varying(255),
    nome character varying(255),
    empresa_id bigint NOT NULL
);


--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tarefa_dependencias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tarefa_dependencias (
    tarefa_id bigint NOT NULL,
    depende_de_id bigint NOT NULL
);


--
-- Name: tarefa_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tarefa_tags (
    tarefa_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: tarefas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tarefas (
    id bigint NOT NULL,
    descricao text,
    prazo date,
    prioridade character varying(255),
    status character varying(255),
    titulo character varying(255),
    projeto_id bigint,
    responsavel_id bigint,
    historia_usuario_id bigint,
    CONSTRAINT tarefas_status_check CHECK (((status)::text = ANY ((ARRAY['A_FAZER'::character varying, 'EM_ANDAMENTO'::character varying, 'CONCLUIDO'::character varying])::text[])))
);


--
-- Name: tarefas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tarefas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tarefas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tokens_redefinicao_senha; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tokens_redefinicao_senha (
    id bigint NOT NULL,
    expira_em timestamp(6) without time zone,
    token character varying(255),
    usado boolean NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: tokens_redefinicao_senha_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tokens_redefinicao_senha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tokens_redefinicao_senha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_habilidades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_habilidades (
    usuario_id bigint NOT NULL,
    habilidade character varying(255)
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    email character varying(255),
    nome character varying(255),
    papel character varying(255),
    senha character varying(255),
    empresa_id bigint NOT NULL,
    cargo character varying(255),
    disponibilidade character varying(255),
    CONSTRAINT usuarios_disponibilidade_check CHECK (((disponibilidade)::text = ANY ((ARRAY['DISPONIVEL'::character varying, 'PARCIAL'::character varying, 'INDISPONIVEL'::character varying])::text[]))),
    CONSTRAINT usuarios_papel_check CHECK (((papel)::text = ANY ((ARRAY['ADMIN'::character varying, 'MEMBRO'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: acoes_automacao acoes_automacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acoes_automacao
    ADD CONSTRAINT acoes_automacao_pkey PRIMARY KEY (id);


--
-- Name: anexos anexos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anexos
    ADD CONSTRAINT anexos_pkey PRIMARY KEY (id);


--
-- Name: comentarios comentarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT comentarios_pkey PRIMARY KEY (id);


--
-- Name: conquistas_usuario conquistas_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conquistas_usuario
    ADD CONSTRAINT conquistas_usuario_pkey PRIMARY KEY (id);


--
-- Name: documentos_projeto documentos_projeto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_projeto
    ADD CONSTRAINT documentos_projeto_pkey PRIMARY KEY (id);


--
-- Name: empresas empresas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id);


--
-- Name: epicos epicos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epicos
    ADD CONSTRAINT epicos_pkey PRIMARY KEY (id);


--
-- Name: historias_usuario historias_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historias_usuario
    ADD CONSTRAINT historias_usuario_pkey PRIMARY KEY (id);


--
-- Name: historico historico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico
    ADD CONSTRAINT historico_pkey PRIMARY KEY (id);


--
-- Name: integracoes_github integracoes_github_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integracoes_github
    ADD CONSTRAINT integracoes_github_pkey PRIMARY KEY (id);


--
-- Name: notificacoes notificacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT notificacoes_pkey PRIMARY KEY (id);


--
-- Name: projetos projetos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT projetos_pkey PRIMARY KEY (id);


--
-- Name: regras_automacao regras_automacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regras_automacao
    ADD CONSTRAINT regras_automacao_pkey PRIMARY KEY (id);


--
-- Name: sprint_burndown_snapshots sprint_burndown_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprint_burndown_snapshots
    ADD CONSTRAINT sprint_burndown_snapshots_pkey PRIMARY KEY (id);


--
-- Name: sprints sprints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprints
    ADD CONSTRAINT sprints_pkey PRIMARY KEY (id);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: tarefas tarefas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefas
    ADD CONSTRAINT tarefas_pkey PRIMARY KEY (id);


--
-- Name: tokens_redefinicao_senha tokens_redefinicao_senha_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_redefinicao_senha
    ADD CONSTRAINT tokens_redefinicao_senha_pkey PRIMARY KEY (id);


--
-- Name: integracoes_github uk4tptred8agv8eyai2eun5q50w; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integracoes_github
    ADD CONSTRAINT uk4tptred8agv8eyai2eun5q50w UNIQUE (projeto_id);


--
-- Name: tags ukdjxnxxdps9xlai6j4757h8n8r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT ukdjxnxxdps9xlai6j4757h8n8r UNIQUE (nome, empresa_id);


--
-- Name: conquistas_usuario uke36cblyfvpuo0quv1x2gq58j3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conquistas_usuario
    ADD CONSTRAINT uke36cblyfvpuo0quv1x2gq58j3 UNIQUE (usuario_id, codigo);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: empresas ukm1yjw6c3yvplkj9iifrfvvl9r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT ukm1yjw6c3yvplkj9iifrfvvl9r UNIQUE (codigo_convite);


--
-- Name: sprint_burndown_snapshots ukojdi8h8kscqpk8f6vtf63f0fo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprint_burndown_snapshots
    ADD CONSTRAINT ukojdi8h8kscqpk8f6vtf63f0fo UNIQUE (sprint_id, data);


--
-- Name: tokens_redefinicao_senha ukqdywhqgta74gsxgwldgvju5kb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_redefinicao_senha
    ADD CONSTRAINT ukqdywhqgta74gsxgwldgvju5kb UNIQUE (token);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuario_habilidades fk18vpi4jo0sba8prmmpjg0d34h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_habilidades
    ADD CONSTRAINT fk18vpi4jo0sba8prmmpjg0d34h FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: sprint_burndown_snapshots fk1evy6wree7n0ch6svr2wnbei4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprint_burndown_snapshots
    ADD CONSTRAINT fk1evy6wree7n0ch6svr2wnbei4 FOREIGN KEY (sprint_id) REFERENCES public.sprints(id);


--
-- Name: tarefa_dependencias fk2qhfavhyuq6h7gx6op0lmuviv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefa_dependencias
    ADD CONSTRAINT fk2qhfavhyuq6h7gx6op0lmuviv FOREIGN KEY (tarefa_id) REFERENCES public.tarefas(id);


--
-- Name: tarefa_tags fk2tn0bs1v3nls9or0l90ilsahn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefa_tags
    ADD CONSTRAINT fk2tn0bs1v3nls9or0l90ilsahn FOREIGN KEY (tarefa_id) REFERENCES public.tarefas(id);


--
-- Name: notificacoes fk3jcnk0ggmxklk5sjxm2plk5ml; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT fk3jcnk0ggmxklk5sjxm2plk5ml FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: documentos_projeto fk5tme8ykg2r5utg4oydjjtncwg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_projeto
    ADD CONSTRAINT fk5tme8ykg2r5utg4oydjjtncwg FOREIGN KEY (criado_por) REFERENCES public.usuarios(id);


--
-- Name: tarefa_dependencias fk66k2vf921ahfpn6elabkss5y2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefa_dependencias
    ADD CONSTRAINT fk66k2vf921ahfpn6elabkss5y2 FOREIGN KEY (depende_de_id) REFERENCES public.tarefas(id);


--
-- Name: projeto_membros fk7idyaqojbj69a03y7slfvl2nc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projeto_membros
    ADD CONSTRAINT fk7idyaqojbj69a03y7slfvl2nc FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: historico fk827tpay46f0s493ya1dknxl2e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico
    ADD CONSTRAINT fk827tpay46f0s493ya1dknxl2e FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: projetos fk93e0x3gi9atyke91abfisbgxb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT fk93e0x3gi9atyke91abfisbgxb FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: usuarios fk9v93lqnass5yqhhsyprr9fdv2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk9v93lqnass5yqhhsyprr9fdv2 FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: projetos fkacg7gti4qid1iblo90vgmuan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projetos
    ADD CONSTRAINT fkacg7gti4qid1iblo90vgmuan FOREIGN KEY (criado_por) REFERENCES public.usuarios(id);


--
-- Name: tarefas fkag5ybvd3asptw0xyadg58t95r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefas
    ADD CONSTRAINT fkag5ybvd3asptw0xyadg58t95r FOREIGN KEY (historia_usuario_id) REFERENCES public.historias_usuario(id);


--
-- Name: historias_usuario fkahxyrd26m04h63o2onvs6kp0n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historias_usuario
    ADD CONSTRAINT fkahxyrd26m04h63o2onvs6kp0n FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: acoes_automacao fkb543vquki9c52q0bckvumu9my; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acoes_automacao
    ADD CONSTRAINT fkb543vquki9c52q0bckvumu9my FOREIGN KEY (regra_id) REFERENCES public.regras_automacao(id);


--
-- Name: projeto_membros fkdrriu0nvklo6mvkn0jiayvd0m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projeto_membros
    ADD CONSTRAINT fkdrriu0nvklo6mvkn0jiayvd0m FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: comentarios fkdts62yj83qe3k748cgcjvm48r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT fkdts62yj83qe3k748cgcjvm48r FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: regras_automacao fkejaoyuh4fs2yd94d64v80vblj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.regras_automacao
    ADD CONSTRAINT fkejaoyuh4fs2yd94d64v80vblj FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: tokens_redefinicao_senha fkg0v6kw9mykajsebnbhu7wyahk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tokens_redefinicao_senha
    ADD CONSTRAINT fkg0v6kw9mykajsebnbhu7wyahk FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: documentos_projeto fkgfroa171orsovf7hdvbm4sec9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos_projeto
    ADD CONSTRAINT fkgfroa171orsovf7hdvbm4sec9 FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: tarefa_tags fkj5r4s85dekdvyjcvnbicrp0vs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefa_tags
    ADD CONSTRAINT fkj5r4s85dekdvyjcvnbicrp0vs FOREIGN KEY (tag_id) REFERENCES public.tags(id);


--
-- Name: conquistas_usuario fkjbn9tn91um5cu2qkotjn6hmnd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conquistas_usuario
    ADD CONSTRAINT fkjbn9tn91um5cu2qkotjn6hmnd FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: historico fkjy8jobsg9471g1rvur5vtvd2h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico
    ADD CONSTRAINT fkjy8jobsg9471g1rvur5vtvd2h FOREIGN KEY (tarefa_id) REFERENCES public.tarefas(id);


--
-- Name: sprints fkkika1lun0rowm9axlm81vxgte; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprints
    ADD CONSTRAINT fkkika1lun0rowm9axlm81vxgte FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: tags fkkydtg4n5p0i2i3whjc9kcjee5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT fkkydtg4n5p0i2i3whjc9kcjee5 FOREIGN KEY (empresa_id) REFERENCES public.empresas(id);


--
-- Name: comentarios fklc82vrhb38c8udoannh9f0vi9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT fklc82vrhb38c8udoannh9f0vi9 FOREIGN KEY (tarefa_id) REFERENCES public.tarefas(id);


--
-- Name: acoes_automacao fklmbfj7m8tul6tlcwl79bm8io6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.acoes_automacao
    ADD CONSTRAINT fklmbfj7m8tul6tlcwl79bm8io6 FOREIGN KEY (tag_id) REFERENCES public.tags(id);


--
-- Name: notificacoes fklx8vk1lb6poh1bel1w480buyv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT fklx8vk1lb6poh1bel1w480buyv FOREIGN KEY (tarefa_id) REFERENCES public.tarefas(id);


--
-- Name: tarefas fkn358o3rmw5wfvr0ide314yebu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefas
    ADD CONSTRAINT fkn358o3rmw5wfvr0ide314yebu FOREIGN KEY (responsavel_id) REFERENCES public.usuarios(id);


--
-- Name: tarefas fknufogsq3m90l1k8r8rf664usn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tarefas
    ADD CONSTRAINT fknufogsq3m90l1k8r8rf664usn FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: historias_usuario fkoygcy9hh1n83mrfac22d2knd1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historias_usuario
    ADD CONSTRAINT fkoygcy9hh1n83mrfac22d2knd1 FOREIGN KEY (sprint_id) REFERENCES public.sprints(id);


--
-- Name: historias_usuario fkp0v1dpn2nj7jym9cthunw0k2f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historias_usuario
    ADD CONSTRAINT fkp0v1dpn2nj7jym9cthunw0k2f FOREIGN KEY (epico_id) REFERENCES public.epicos(id);


--
-- Name: integracoes_github fkpsoxg4e0vpxgvvlt8k00t4ftg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integracoes_github
    ADD CONSTRAINT fkpsoxg4e0vpxgvvlt8k00t4ftg FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- Name: anexos fkqv0kbb8ora8h2qqrrebhetycs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anexos
    ADD CONSTRAINT fkqv0kbb8ora8h2qqrrebhetycs FOREIGN KEY (tarefa_id) REFERENCES public.tarefas(id);


--
-- Name: epicos fkrgq2l7bwg89j2m5onuhoim17f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.epicos
    ADD CONSTRAINT fkrgq2l7bwg89j2m5onuhoim17f FOREIGN KEY (projeto_id) REFERENCES public.projetos(id);


--
-- PostgreSQL database dump complete
--


