spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=fabi2511

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MinhaChaveSecretaTaskFlow2026MinhaChaveSecreta123
jwt.expiration=86400000

app.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-3.5-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/interactions